version: "2.3"
services:
  kneel:
    runtime: nvidia
    image: "miptmloulu/kneel:gpu"
    ports:
      - "5000:5000"
    container_name: kneel
    volumes:
      - type: bind
        source: ../snapshots_release_kneel # The snapshots are stored in the root directory
        target: /snapshots/
        read_only: true
      - type: bind
        source: ../logs
        target: /logs/
    entrypoint: ["python", "-u", "-m", "kneel.inference.app",
       "--lc_snapshot_path", "/snapshots/lext-devbox_2019_07_14_16_04_41",
      "--hc_snapshot_path", "/snapshots/lext-devbox_2019_07_14_19_25_40",
      "--refine", "True", "--mean_std_path", "/snapshots/mean_std.npy",
      "--deploy", "True", "--device", "cuda", 
      "--port", "5000", "--logs", "/logs/kneel-gpu.log"]
  deepknee-backend:
    runtime: nvidia
    depends_on:
      - kneel
    image: "miptmloulu/deepknee:gpu"
    ports:
      - "5001:5001"
    container_name: deepknee
    volumes:
      - type: bind
        source: ../snapshots_knee_grading/ # The snapshots are stored in the root directory
        target: /snapshots/
        read_only: true
      - type: bind
        source: ../logs
        target: /logs/
    environment:
      - KNEEL_ADDR=http://kneel:5000
    entrypoint: ["python", "-m", "ouludeepknee.inference.app",
                 "--snapshots_path", "/snapshots/",
                 "--device", "cuda", "--deploy", "True",
                 "--port", "5001", "--deploy_addr", "0.0.0.0",
                 "--logs", "/logs/deepknee-gpu.log"]
  orthanc-pacs:
    depends_on:
      - kneel
      - deepknee-backend
    image: "jodogne/orthanc"
    container_name: orthanc-pacs
    ports:
      - "6000:4242"
      - "6001:8042"
    volumes:
      - type: bind
        source: ../pacs-integration/orthanc.json
        target: /etc/orthanc/orthanc.json
  dicom-router:
    depends_on:
      kneel:
        condition: service_started
      deepknee-backend:
        condition: service_started
      orthanc-pacs:
        condition: service_started
    image: "miptmloulu/deepknee:cpu"
    container_name: dicom-router
    volumes:
      - type: bind
        source: ../pacs-integration/change_polling.py
        target: /opt/change_polling.py
    entrypoint: ["python", "-u", "/opt/change_polling.py",
                 "--deepknee_addr", "http://deepknee",
                 "--deepknee_port", "5001",
                 "--orthanc_addr", "http://orthanc-pacs",
                 "--orthanc_http_port", "8042",
                 "--orthanc_dicom_port", "4242",
                 '--remote_pacs_addr', 'orthanc-pacs',
                 '--remote_pacs_port', '4242']
  backend-broker:
    depends_on:
      - kneel
      - deepknee-backend
    image: "miptmloulu/deepknee:broker"
    container_name: backend-broker
    ports:
      - "5002:5002"
    environment:
      - DEPLOY_HOST=0.0.0.0
      - DEPLOY_PORT=5002
      - KNEEL_ADDR=http://kneel
      - KNEEL_PORT=5000
      - DEEPKNEE_ADDR=http://deepknee-backend
      - DEEPKNEE_PORT=5001
    entrypoint: ["node", "/usr/src/app/server.js"]
  ui:
    depends_on:
      - kneel
      - deepknee-backend
      - backend-broker
    image: "miptmloulu/deepknee:ui"
    container_name: ui
    ports:
      - "5003:5003"
    entrypoint: ["serve", "-l", "5003", "-s", "/usr/src/app/build"]
