version: 2
jobs:
  py3test:
    working_directory: ~/megnet
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:3.7.3 
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            pip install pip --upgrade
            pip install --quiet pycodestyle
            export PATH=$HOME/miniconda3/bin:$PATH
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda create -q -n test-environment python=3.7 numpy scipy matplotlib sympy cython tensorflow
            source activate test-environment
            conda update --quiet --yes numpy scipy matplotlib sympy cython tensorflow 
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt
            conda install -c openbabel openbabel
            conda install -c conda-forge rdkit
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate test-environment
            pip install --quiet -e .
            pytest --cov=megnet --cov-report html:coverage_reports megnet
            pycodestyle megnet
            coveralls
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
