UNET:
    dataset: 'nih'
    lr: 0.0025
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "Ternary" # "INT", "BNN", "Normal", "FIXED", "XNOR", "Ternary"
    gpu_core_num: 0
    dropout: "enable" # disable
    activation: "relu" #"ternarytanh"
    trained_model: "/export/tmp/hemmat/results/nih_ternary/nih_ternary.pkl"
    experiment_name: "nih_ternaryi_lr_0025"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" # normal, visualize, retrain, inference
    # trained_model: ""
