UNET:
    dataset: 'gmchallenge'
    lr: 0.001
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "Fixed" # "INT", "BNN", "Normal"
    activation_f_width: 0
    activation_i_width: 4
    weight_f_width: 2
    weight_i_width: 0
    dropout: "false"
    activation: "tanh"
    gpu_core_num: 2
    trained_model: "/export/tmp/hemmat/results/gm_tanh_a4_0_w0_2/gm_tanh_a4_0_w0_2.pkl"
    experiment_name: "gm_tanh_a4_0_w0_2"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" #visualize
    # trained_model: ""
