 version: '3'
 services:
   db:
     image: postgres
     volumes:
      - chpgdata:/var/lib/postgresql/data
   rabbit:
     image: rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=chuser
       - RABBITMQ_DEFAULT_PASS=chpass
     volumes:
       - chrabbit:/var/lib/rabbitmq
   ch:
     build: .
     container_name: computational-healthcare
     image: computationalhealthcare:latest
     command: bash -c "git pull && fab start_server"
     ports:
       - "8188:8888"
       - "8111:8000"
     depends_on:
       - db
       - rabbit
     volumes:
       - chdata:/root/data
 volumes:
  chdata:
  chpgdata:
  chrabbit: