UNET:
    dataset: 'gmchallenge'
    lr: 0.0001
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED"
    activation_f_width: 0
    activation_i_width: 8
    weight_f_width: 8
    weight_i_width: 0
    gpu_core_num: 0
    dropout: "enable" # disable
    trained_model: "/export/tmp/hemmat/results/full_precision/full_precision.pkl"
    experiment_name: "a8_0_w0_8_with_dropout"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" # normal, visualize, retrain, inference
    # trained_model: ""
