train:
  data_provider:
    unlabeled_train:
      cate: MixUpSampler
      num_samples: 1
      data_key: "mixup_data"
      target_key:
        - "logits_mixup"
        - "name"
    labeled_train:
      cate: ItemLoader
      num_samples: 1
      data_key: "data"
      target_key:
        - "target"
        - "name"

eval:
  data_provider:
    labeled_eval:
      cate: ItemLoader
      num_samples: 1
      data_key: "data"
      target_key:
        - "target"
        - "name"

    unlabeled_eval:
      cate: MixUpSampler
      num_samples: 1
      data_key: "mixup_data"
      target_key:
        - "logits_mixup"
        - "name"
