UNET:
    dataset: 'gmchallenge'
    lr: 0.001
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED"
    activation_f_width: 0
    activation_i_width: 4
    weight_f_width: 3
    weight_i_width: 0
    gpu_core_num: 1
    trained_model: "/export/tmp/hemmat/results/full_precision/full_precision.pkl"
    experiment_name: "a4_0_w0_4"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "visualize" # normal, visualize, retrain, inference
    # trained_model: ""
