UNET:
    dataset: 'gmchallenge'
    lr: 0.001
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED"
    activation_f_width: 8
    activation_i_width: 8
    weight_f_width: 8
    weight_i_width: 8
    gpu_core_num: 2
    activation: "tanh"
    dropout: "false"
    trained_model: "/export/tmp/hemmat/results/gm_tanh_a8_8_w8_8/gm_tanh_a8_8_w8_8.pkl"
    experiment_name: "gm_tanh_a8_8_w8_8"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" # normal, visualize, retrain, inference
    # trained_model: ""
