UNET:
    dataset: 'nih'
    lr: 0.001
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED" 
    activation_f_width: 0 
    activation_i_width: 6 
    weight_f_width: 4 
    weight_i_width: 0     
    gpu_core_num: 1
    dropout: "enable" # disable
    activation: "relu"
    trained_model: "/export/tmp/hemmat/results/nih_a6_0_w0_4/nih_a6_0_w0_4.pkl"
    experiment_name: "nih_a6_0_w0_4"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" # normal, visualize, retrain, inference
    # trained_model: ""
