# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0002_codecounts_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
        migrations.RenameModel(
            old_name='CodeCounts',
            new_name='CodeCount',
        ),
        migrations.RenameModel(
            old_name='Datasets',
            new_name='Dataset',
        ),
    ]
