# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 23:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0004_auto_20161025_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('patients_count', models.IntegerField(default=0)),
                ('linked_count', models.IntegerField(default=0)),
                ('unlinked_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='STCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('visit_type', models.PositiveSmallIntegerField()),
                ('linked_count', models.IntegerField(default=0)),
                ('unlinked_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SYTCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('linked', models.BooleanField(default=False)),
                ('visit_type', models.PositiveSmallIntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='codecount',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CH3.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='base_dir',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='linked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='patients_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='unlinked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='n1entry',
            name='computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='n2entry',
            name='computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='n3entry',
            name='computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codecount',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH3.Code'),
        ),
        migrations.AlterField(
            model_name='codecount',
            name='visit_type',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='n1entry',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='n2entry',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='n3entry',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sytcount',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH3.Dataset'),
        ),
        migrations.AddField(
            model_name='stcount',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH3.Dataset'),
        ),
        migrations.AddField(
            model_name='scount',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH3.Dataset'),
        ),
    ]
