# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0005_auto_20161025_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stcount',
            old_name='linked_count',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='stcount',
            name='unlinked_count',
        ),
        migrations.AddField(
            model_name='stcount',
            name='linked',
            field=models.BooleanField(default=False),
        ),
    ]
