# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0009_auto_20161027_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecount',
            name='dataset',
        ),
        migrations.AddField(
            model_name='codecount',
            name='dataset_identifier',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codecount',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
