# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0010_auto_20161027_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='N1Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('delta_median', models.IntegerField(default=-1)),
                ('filename', models.CharField(default='', max_length=200)),
                ('pediatric', models.BooleanField(default=False)),
                ('pediatric_count', models.IntegerField(default=0)),
                ('pediatric_delta_median', models.IntegerField(default=-1)),
                ('key', models.CharField(max_length=100)),
                ('computed', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH3.Dataset')),
            ],
        ),
        migrations.RemoveField(
            model_name='n1entry',
            name='split_code',
        ),
    ]
