# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0014_auto_20161107_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='n2group',
            name='index_filename',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
