# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0016_auto_20161108_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n4entry',
            old_name='count',
            new_name='patients',
        ),
        migrations.RenameField(
            model_name='n4group',
            old_name='count',
            new_name='patients',
        ),
        migrations.AddField(
            model_name='n4entry',
            name='excluded',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
