# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0017_auto_20161108_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='N3Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('index_count', models.IntegerField(default=0)),
                ('unlinked_count', models.IntegerField(default=0)),
                ('revisit_30_count', models.IntegerField(default=0)),
                ('revisit_90_count', models.IntegerField(default=0)),
                ('index_key', models.CharField(max_length=100)),
                ('computed', models.BooleanField(default=False)),
                ('excluded_index', models.TextField()),
                ('excluded_edges', models.TextField()),
                ('excluded_unlinked', models.TextField()),
                ('index_filename', models.CharField(max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH3.Dataset')),
            ],
        ),
    ]
