# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CH3', '0019_n3entry_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='aggregate_patients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='aggregate_readmits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='aggregate_revisits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='aggregate_visits',
            field=models.BooleanField(default=False),
        ),
    ]
