UNET:
    dataset: 'gmchallenge'
    lr: 0.0001
    num_epochs: 400
    model_type: "unet"
    init_type: glorot
    quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED"
    activation_f_width: 0
    activation_i_width: 2
    weight_f_width: 2
    weight_i_width: 0
    gpu_core_num: 2
    trained_model: "/export/tmp/hemmat/results/full_precision/full_precision.pkl"
    experiment_name: "a2_0_w0_2"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" # normal, visualize, retrain, inference
    # trained_model: ""
