UNET:
    dataset: 'gmchallenge'
    lr: 0.001
    num_epochs: 200
    model_type: "unet"
    init_type: glorot
    quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED"
    activation_f_width: 0
    activation_i_width: 6
    weight_f_width: 2
    weight_i_width: 0
    gpu_core_num: 1
    trained_model: "/export/tmp/hemmat/results/em_fullprecision/em_a4_4_w4_4.pkl"
    experiment_name: "em_a6_0_w0_2"
    log_output_dir: "/export/tmp/hemmat/results/"
    operation_mode: "normal" # normal, visualize, retrain, inference
    # trained_model: ""
